name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ensure multipart package present to avoid Starlette warning in tests
          python -m pip install python-multipart
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: Prepare DB env
        run: |
          echo "URN_DB_URL=sqlite:///./ci.db" >> $GITHUB_ENV
      - name: Run tests
        run: |
          python -m pytest -q
